### ISSUE TITLE
Update `node-sass` when it updates `request` to remove vulnerable `hoek` dependency

### ISSUE THREAD

**Issue by charlex** [ShorensteinCenter/Benchmarks-Program#2]
https://github.com/sass/node-sass/pull/2170

**Comment by williamhakim10** [comment]
@charlex `node-sass` is still getting flagged as having vulnerabilities due to `node-gyp` also relying on request which has the same prototype pollution vulnerability. This issue should remain open as we are waiting on a `node-gyp`.

Here's the relevant `node-sass` issue: https://github.com/sass/node-sass/issues/2355

Do note that `gulp-sass` doesn't actually have access to live code, so this bug isn't really a huge deal apart from making npm/github shut up.

**Comment by williamhakim10** [comment]
Fixed with latest Node updates
